### 토크나이저

In [1]:
from transformers import AutoTokenizer

checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much"
]

inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf")

In [2]:
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102],
       [  101,  1045,  5223,  2023,  2061,  2172,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>}


In [3]:
tokens = [tokenizer.tokenize(sentence) for sentence in raw_inputs]
ids = [tokenizer.convert_tokens_to_ids(token) for token in tokens]

print(ids[0])
print(ids[1])
print(tokenizer(raw_inputs, padding=True))

[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]
[1045, 5223, 2023, 2061, 2172]
{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 1045, 5223, 2023, 2061, 2172, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}


In [4]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

inputs = tokenizer("Let's try to tokenize!")

print(inputs['input_ids'])

[101, 2292, 1005, 1055, 3046, 2000, 19204, 4697, 999, 102]


In [5]:
print(tokenizer.decode(inputs["input_ids"]))

[CLS] let ' s try to tokenize! [SEP]


Word2Vec

In [6]:
from gensim.models import Word2Vec

# 텍스트 데이터를 전처리하여 단어의 시퀀스로 변환
sentences = [['I', 'love', 'NLP'], ['Word2Vec', 'is', 'awesome']]

# Word2Vec 모델 학습
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1)

# 단어의 벡터 표현 확인
vector = model.wv['NLP']
print(vector)

[-8.2426779e-03  9.2993546e-03 -1.9766092e-04 -1.9672764e-03
  4.6036304e-03 -4.0953159e-03  2.7431143e-03  6.9399667e-03
  6.0654259e-03 -7.5107943e-03  9.3823504e-03  4.6718083e-03
  3.9661205e-03 -6.2435055e-03  8.4599797e-03 -2.1501649e-03
  8.8251876e-03 -5.3620026e-03 -8.1294188e-03  6.8245591e-03
  1.6711927e-03 -2.1985089e-03  9.5136007e-03  9.4938548e-03
 -9.7740470e-03  2.5052286e-03  6.1566923e-03  3.8724565e-03
  2.0227872e-03  4.3050171e-04  6.7363144e-04 -3.8206363e-03
 -7.1402504e-03 -2.0888723e-03  3.9238976e-03  8.8186832e-03
  9.2591504e-03 -5.9759365e-03 -9.4026709e-03  9.7643770e-03
  3.4297847e-03  5.1661171e-03  6.2823449e-03 -2.8042626e-03
  7.3227035e-03  2.8302716e-03  2.8710044e-03 -2.3803699e-03
 -3.1282497e-03 -2.3701417e-03  4.2764368e-03  7.6057913e-05
 -9.5842788e-03 -9.6655441e-03 -6.1481940e-03 -1.2856961e-04
  1.9974159e-03  9.4319675e-03  5.5843508e-03 -4.2906962e-03
  2.7831673e-04  4.9643586e-03  7.6983096e-03 -1.1442233e-03
  4.3234206e-03 -5.81437

In [8]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\main\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [9]:
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec

# 문장 데이터
sentences = [
    'I love natural language processing',
    'Word2Vec is a popular wold embedding model',
    'Natural language processing is an important field in AI'
]

# 문장을 토큰화
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]
print(tokenized_sentences)

[['I', 'love', 'natural', 'language', 'processing'], ['Word2Vec', 'is', 'a', 'popular', 'wold', 'embedding', 'model'], ['Natural', 'language', 'processing', 'is', 'an', 'important', 'field', 'in', 'AI']]


In [10]:
# Word2Vec 모델 학습
model = Word2Vec(tokenized_sentences, vector_size=100, window=5, min_count=1)

# 단어의 벡터 표현 확인
word_vectors = model.wv
print(word_vectors['language']) # 'language' 단어의 벡터 출력

[-5.3780823e-04  2.3722864e-04  5.1040910e-03  9.0102609e-03
 -9.3020601e-03 -7.1179681e-03  6.4588394e-03  8.9740995e-03
 -5.0159963e-03 -3.7642447e-03  7.3804674e-03 -1.5347273e-03
 -4.5378106e-03  6.5551274e-03 -4.8596673e-03 -1.8148653e-03
  2.8774342e-03  9.9292281e-04 -8.2860254e-03 -9.4493292e-03
  7.3125120e-03  5.0700661e-03  6.7592775e-03  7.6191645e-04
  6.3517732e-03 -3.4046052e-03 -9.4711396e-04  5.7690116e-03
 -7.5220009e-03 -3.9353538e-03 -7.5102169e-03 -9.3084743e-04
  9.5383907e-03 -7.3201652e-03 -2.3331069e-03 -1.9370844e-03
  8.0786459e-03 -5.9302277e-03  4.5893696e-05 -4.7526849e-03
 -9.6026389e-03  5.0062062e-03 -8.7609617e-03 -4.3915613e-03
 -3.5224024e-05 -2.9514002e-04 -7.6609026e-03  9.6143829e-03
  4.9826237e-03  9.2333835e-03 -8.1571704e-03  4.4943946e-03
 -4.1372897e-03  8.2511746e-04  8.4984917e-03 -4.4609406e-03
  4.5189071e-03 -6.7863516e-03 -3.5486098e-03  9.3998490e-03
 -1.5785332e-03  3.2206855e-04 -4.1410322e-03 -7.6832231e-03
 -1.5072766e-03  2.47044